const css = require("./index.css");

import React from "react";
import ReactDOM from "react-dom";

ReactDOM.render(
    <h1>This contenet Generated by react.</h1>,
    document.getElementById("react-root")
);